In [1]:
# 1. Importing the libraries 
import numpy as np 
import pandas as pd

In [2]:
# 2. Reading the datasets 
data = pd.read_csv('bank.csv')

In [3]:
data.head(30)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
5,42,management,single,tertiary,no,0,yes,yes,unknown,5,may,562,2,-1,0,unknown,yes
6,56,management,married,tertiary,no,830,yes,yes,unknown,6,may,1201,1,-1,0,unknown,yes
7,60,retired,divorced,secondary,no,545,yes,no,unknown,6,may,1030,1,-1,0,unknown,yes
8,37,technician,married,secondary,no,1,yes,no,unknown,6,may,608,1,-1,0,unknown,yes
9,28,services,single,secondary,no,5090,yes,no,unknown,6,may,1297,3,-1,0,unknown,yes
10,38,admin.,single,secondary,no,100,yes,no,unknown,7,may,786,1,-1,0,unknown,yes
11,30,blue-collar,married,secondary,no,309,yes,no,unknown,7,may,1574,2,-1,0,unknown,yes
12,29,management,married,tertiary,no,199,yes,yes,unknown,7,may,1689,4,-1,0,unknown,yes
13,46,blue-collar,single,tertiary,no,460,yes,no,unknown,7,may,1102,2,-1,0,unknown,yes
14,31,technician,single,tertiary,no,703,yes,no,unknown,8,may,943,2,-1,0,unknown,yes
15,35,management,divorced,tertiary,no,3837,yes,no,unknown,8,may,1084,1,-1,0,unknown,yes
16,32,blue-collar,single,primary,no,611,yes,no,unknown,8,may,541,3,-1,0,unknown,yes
17,49,services,married,secondary,no,-8,yes,no,unknown,8,may,1119,1,-1,0,unknown,yes
18,41,admin.,married,secondary,no,55,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
19,49,admin.,divorced,secondary,no,168,yes,yes,unknown,8,may,513,1,-1,0,unknown,yes
20,28,admin.,divorced,secondary,no,785,yes,no,unknown,8,may,442,2,-1,0,unknown,yes
21,43,management,single,tertiary,no,2067,yes,no,unknown,8,may,756,1,-1,0,unknown,yes
22,43,management,divorced,tertiary,no,388,yes,no,unknown,8,may,2087,2,-1,0,unknown,yes
23,43,blue-collar,married,primary,no,-192,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
24,37,unemployed,single,secondary,no,381,yes,no,unknown,8,may,985,2,-1,0,unknown,yes
25,35,blue-collar,single,secondary,no,40,yes,no,unknown,9,may,617,4,-1,0,unknown,yes
26,31,technician,single,tertiary,no,22,yes,no,unknown,9,may,483,3,-1,0,unknown,yes
27,43,blue-collar,single,secondary,no,3,yes,no,unknown,9,may,929,3,-1,0,unknown,yes
28,31,admin.,married,secondary,no,307,yes,no,unknown,9,may,538,1,-1,0,unknown,yes
29,28,blue-collar,single,secondary,no,759,yes,no,unknown,9,may,710,1,-1,0,unknown,yes

In [4]:
# 3. Handling missing values 
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
# 4. Splitting data into inputs and outputs
inputs = data.iloc[:, :16].values
outputs = data.iloc[:, -1:].values

In [6]:

inputs[0:2]

array([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
        'unknown', 5, 'may', 1042, 1, -1, 0, 'unknown'],
       [56, 'admin.', 'married', 'secondary', 'no', 45, 'no', 'no',
        'unknown', 5, 'may', 1467, 1, -1, 0, 'unknown']], dtype=object)

In [7]:
outputs.shape

(11162, 1)

In [8]:

outputs

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [9]:
# Importing libraries to handle the categorical data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [10]:
# 5. Handling categorical data 
ct = ColumnTransformer([('one', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
inputs = ct.fit_transform(inputs)

cto = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
outputs = cto.fit_transform(outputs)

In [11]:
inputs.shape

(11162, 51)

In [12]:
inputs

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [13]:
outputs

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [14]:

# Importing libraries to handle splitting 
from sklearn.model_selection import train_test_split

In [15]:
# 6. Splitting data to train and test sets
x_train,x_test,y_train,y_test = train_test_split(inputs,outputs,test_size = 0.2, random_state = 0)

In [16]:
print('Inputs shape ', inputs.shape)
print('Outputs shape ', outputs.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (11162, 51)
Outputs shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)

In [17]:
# Importing libraries to handle feature scaling 
from sklearn.preprocessing import StandardScaler

In [18]:
# 7. Applying feature scaling 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [20]:
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         2.62409874,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         1.30248101,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.51893725,
        -0.46885387, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612]])

In [21]:
# Import deep learning libraries
from tensorflow.keras.models import Sequential  
from tensorflow.keras.layers import Dense

In [22]:
categorical = Sequential()

In [25]:

# Input layer
categorical.add(Dense(units = 51, kernel_initializer = 'random_uniform', activation = 'relu'))

In [26]:
# Hidden layer 1  
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [27]:
# Hidden layer 2
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [28]:

# Output layer 
categorical.add(Dense(units = 2, kernel_initializer = 'random_uniform', activation = 'softmax'))

In [29]:
# Compiling model  
categorical.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
# Compiling model  
categorical.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [31]:
# Training the model 
categorical.fit(x_train, y_train, epochs = 150)

Epoch 1/150
8929/8929 [==============================] - 1s 147us/sample - loss: 0.4649 - acc: 0.7636
Epoch 2/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.3637 - acc: 0.8463
Epoch 3/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.3483 - acc: 0.8582
Epoch 4/150
8929/8929 [==============================] - 1s 98us/sample - loss: 0.3370 - acc: 0.8618
Epoch 5/150
8929/8929 [==============================] - 1s 109us/sample - loss: 0.3277 - acc: 0.8673
Epoch 6/150
8929/8929 [==============================] - 1s 108us/sample - loss: 0.3226 - acc: 0.8676
Epoch 7/150
8929/8929 [==============================] - 1s 99us/sample - loss: 0.3165 - acc: 0.8696
Epoch 8/150
8929/8929 [==============================] - 1s 98us/sample - loss: 0.3078 - acc: 0.8740
Epoch 9/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.3045 - acc: 0.8771
Epoch 10/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.3053 - acc: 0.8734
Epoch 11/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.2930 - acc: 0.8821
Epoch 12/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.2867 - acc: 0.8849
Epoch 13/150
8929/8929 [==============================] - 1s 82us/sample - loss: 0.2844 - acc: 0.8869
Epoch 14/150
8929/8929 [==============================] - 1s 82us/sample - loss: 0.2781 - acc: 0.8881
Epoch 15/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.2766 - acc: 0.8897
Epoch 16/150
8929/8929 [==============================] - 1s 103us/sample - loss: 0.2716 - acc: 0.8920
Epoch 17/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.2659 - acc: 0.8908
Epoch 18/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.2644 - acc: 0.8936
Epoch 19/150
8929/8929 [==============================] - 1s 99us/sample - loss: 0.2585 - acc: 0.8954
Epoch 20/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.2570 - acc: 0.8964
Epoch 21/150
8929/8929 [==============================] - 1s 85us/sample - loss: 0.2490 - acc: 0.8981
Epoch 22/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.2413 - acc: 0.9028
Epoch 23/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.2441 - acc: 0.9008
Epoch 24/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.2329 - acc: 0.9046
Epoch 25/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.2312 - acc: 0.9049
Epoch 26/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.2248 - acc: 0.9054
Epoch 27/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.2209 - acc: 0.9072
Epoch 28/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.2155 - acc: 0.9095
Epoch 29/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.2140 - acc: 0.9087
Epoch 30/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.2057 - acc: 0.9138
Epoch 31/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.1981 - acc: 0.9163
Epoch 32/150
8929/8929 [==============================] - 1s 98us/sample - loss: 0.1972 - acc: 0.9160
Epoch 33/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.1949 - acc: 0.9181
Epoch 34/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.1900 - acc: 0.9207
Epoch 35/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.1803 - acc: 0.9217
Epoch 36/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.1798 - acc: 0.9238
Epoch 37/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.1720 - acc: 0.9277
Epoch 38/150
8929/8929 [==============================] - 1s 99us/sample - loss: 0.1725 - acc: 0.9287
Epoch 39/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.1627 - acc: 0.9337
Epoch 40/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.1640 - acc: 0.9318
Epoch 41/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.1526 - acc: 0.9372
Epoch 42/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.1536 - acc: 0.9357
Epoch 43/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.1447 - acc: 0.9432
Epoch 44/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.1481 - acc: 0.9385
Epoch 45/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.1401 - acc: 0.9439
Epoch 46/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.1305 - acc: 0.9470
Epoch 47/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.1612 - acc: 0.9353
Epoch 48/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.1307 - acc: 0.9484
Epoch 49/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.1305 - acc: 0.9457
Epoch 50/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.1231 - acc: 0.9522
Epoch 51/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.1207 - acc: 0.9554
Epoch 52/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.1221 - acc: 0.9503
Epoch 53/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.1145 - acc: 0.9524
Epoch 54/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.1121 - acc: 0.9553
Epoch 55/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.1053 - acc: 0.9578
Epoch 56/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.1063 - acc: 0.9588
Epoch 57/150
8929/8929 [==============================] - 1s 102us/sample - loss: 0.1016 - acc: 0.9612
Epoch 58/150
8929/8929 [==============================] - 1s 102us/sample - loss: 0.1028 - acc: 0.9604
Epoch 59/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0995 - acc: 0.9617
Epoch 60/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.1017 - acc: 0.9599
Epoch 61/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0958 - acc: 0.9638
Epoch 62/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0874 - acc: 0.9649
Epoch 63/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0960 - acc: 0.9619
Epoch 64/150
8929/8929 [==============================] - 1s 100us/sample - loss: 0.0915 - acc: 0.9660
Epoch 65/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0788 - acc: 0.9702
Epoch 66/150
8929/8929 [==============================] - 1s 80us/sample - loss: 0.0855 - acc: 0.9686
Epoch 67/150
8929/8929 [==============================] - 1s 82us/sample - loss: 0.0784 - acc: 0.9703
Epoch 68/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0746 - acc: 0.9709
Epoch 69/150
8929/8929 [==============================] - 1s 101us/sample - loss: 0.0812 - acc: 0.9693
Epoch 70/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0854 - acc: 0.9679
Epoch 71/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0748 - acc: 0.9729
Epoch 72/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0724 - acc: 0.9732
Epoch 73/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0715 - acc: 0.9719
Epoch 74/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0683 - acc: 0.9737
Epoch 75/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0704 - acc: 0.9739
Epoch 76/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0749 - acc: 0.9732
Epoch 77/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0663 - acc: 0.9761
Epoch 78/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0665 - acc: 0.9746
Epoch 79/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0623 - acc: 0.9754
Epoch 80/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0607 - acc: 0.9769
Epoch 81/150

8929/8929 [==============================] - 1s 91us/sample - loss: 0.0673 - acc: 0.9739
Epoch 82/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0667 - acc: 0.9761
Epoch 83/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0666 - acc: 0.9748
Epoch 84/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0599 - acc: 0.9767
Epoch 85/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0501 - acc: 0.9824
Epoch 86/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0628 - acc: 0.9774
Epoch 87/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0591 - acc: 0.9782
Epoch 88/150
8929/8929 [==============================] - 1s 85us/sample - loss: 0.0613 - acc: 0.9776
Epoch 89/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0542 - acc: 0.9815
Epoch 90/150
8929/8929 [==============================] - 1s 85us/sample - loss: 0.0508 - acc: 0.9815
Epoch 91/150
8929/8929 [==============================] - 1s 83us/sample - loss: 0.0551 - acc: 0.9802
Epoch 92/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0562 - acc: 0.9784
Epoch 93/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0478 - acc: 0.9820
Epoch 94/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0652 - acc: 0.9766
Epoch 95/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0538 - acc: 0.9802
Epoch 96/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0525 - acc: 0.9792
Epoch 97/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0552 - acc: 0.9802
Epoch 98/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0484 - acc: 0.9817
Epoch 99/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0409 - acc: 0.9866
Epoch 100/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0578 - acc: 0.9780
Epoch 101/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0559 - acc: 0.9803
Epoch 102/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0446 - acc: 0.9830
Epoch 103/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0427 - acc: 0.9850
Epoch 104/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0524 - acc: 0.9819
Epoch 105/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0413 - acc: 0.9863
Epoch 106/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0460 - acc: 0.9829
Epoch 107/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0382 - acc: 0.9868
Epoch 108/150
8929/8929 [==============================] - 1s 82us/sample - loss: 0.0529 - acc: 0.9808
Epoch 109/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0445 - acc: 0.9839
Epoch 110/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0430 - acc: 0.9825
Epoch 111/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0404 - acc: 0.9843
Epoch 112/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0460 - acc: 0.9850
Epoch 113/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0423 - acc: 0.9861
Epoch 114/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0428 - acc: 0.9842
Epoch 115/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0378 - acc: 0.9871
Epoch 116/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0566 - acc: 0.9780
Epoch 117/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0346 - acc: 0.9877
Epoch 118/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0428 - acc: 0.9858
Epoch 119/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0402 - acc: 0.9858
Epoch 120/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0434 - acc: 0.9848
Epoch 121/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0351 - acc: 0.9876
Epoch 122/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0460 - acc: 0.9836
Epoch 123/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0393 - acc: 0.9870
Epoch 124/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0346 - acc: 0.9876
Epoch 125/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0327 - acc: 0.9877
Epoch 126/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0305 - acc: 0.9905
Epoch 127/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0425 - acc: 0.9854
Epoch 128/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0359 - acc: 0.9887
Epoch 129/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0280 - acc: 0.9903
Epoch 130/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0415 - acc: 0.9856
Epoch 131/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0394 - acc: 0.9858
Epoch 132/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0296 - acc: 0.9891
Epoch 133/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0396 - acc: 0.9856
Epoch 134/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0384 - acc: 0.9870
Epoch 135/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0377 - acc: 0.9864
Epoch 136/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0367 - acc: 0.9866
Epoch 137/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0563 - acc: 0.98030s - loss: 0.0909 -
Epoch 138/150
8929/8929 [==============================] - 1s 86us/sample - loss: 0.0270 - acc: 0.9898
Epoch 139/150
8929/8929 [==============================] - 1s 85us/sample - loss: 0.0341 - acc: 0.9879
Epoch 140/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0482 - acc: 0.9832
Epoch 141/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0286 - acc: 0.9904
Epoch 142/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0262 - acc: 0.9901
Epoch 143/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0413 - acc: 0.9867
Epoch 144/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0321 - acc: 0.9897
Epoch 145/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0378 - acc: 0.9871
Epoch 146/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0191 - acc: 0.9931
Epoch 147/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0319 - acc: 0.9885
Epoch 148/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0310 - acc: 0.9905
Epoch 149/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0293 - acc: 0.9895
Epoch 150/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0319 - acc: 0.9891

In [32]:
# Training the model 
categorical.fit(x_train, y_train, epochs = 150)

Epoch 1/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0331 - acc: 0.9871
Epoch 2/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0340 - acc: 0.9872
Epoch 3/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0294 - acc: 0.9907
Epoch 4/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0347 - acc: 0.9875
Epoch 5/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0351 - acc: 0.9880
Epoch 6/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0228 - acc: 0.9920
Epoch 7/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0256 - acc: 0.9901
Epoch 8/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0340 - acc: 0.9884
Epoch 9/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0276 - acc: 0.9900
Epoch 10/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0269 - acc: 0.9916
Epoch 11/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0360 - acc: 0.9886
Epoch 12/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0198 - acc: 0.9936
Epoch 13/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0252 - acc: 0.9912
Epoch 14/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0343 - acc: 0.9869
Epoch 15/150
8929/8929 [==============================] - 1s 83us/sample - loss: 0.0366 - acc: 0.9863
Epoch 16/150
8929/8929 [==============================] - 1s 83us/sample - loss: 0.0279 - acc: 0.9912
Epoch 17/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0339 - acc: 0.9878
Epoch 18/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0277 - acc: 0.9897
Epoch 19/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0253 - acc: 0.9914
Epoch 20/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0224 - acc: 0.9927
Epoch 21/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0260 - acc: 0.9904
Epoch 22/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0523 - acc: 0.9823
Epoch 23/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0261 - acc: 0.99140s - loss: 0.0235
Epoch 24/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0210 - acc: 0.9934
Epoch 25/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0186 - acc: 0.9925
Epoch 26/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0323 - acc: 0.9897
Epoch 27/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0325 - acc: 0.9879
Epoch 28/150
8929/8929 [==============================] - 1s 101us/sample - loss: 0.0240 - acc: 0.9923
Epoch 29/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0168 - acc: 0.9954
Epoch 30/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0252 - acc: 0.9916
Epoch 31/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0257 - acc: 0.9905
Epoch 32/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0293 - acc: 0.9896
Epoch 33/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0190 - acc: 0.9936
Epoch 34/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0332 - acc: 0.9888
Epoch 35/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0244 - acc: 0.9917
Epoch 36/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0193 - acc: 0.9937
Epoch 37/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0229 - acc: 0.9920
Epoch 38/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0309 - acc: 0.9890
Epoch 39/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0247 - acc: 0.9914
Epoch 40/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0279 - acc: 0.9906
Epoch 41/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0292 - acc: 0.9906
Epoch 42/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0261 - acc: 0.9909
Epoch 43/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0155 - acc: 0.9954
Epoch 44/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0284 - acc: 0.9912
Epoch 45/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0272 - acc: 0.9912
Epoch 46/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0150 - acc: 0.9957
Epoch 47/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0239 - acc: 0.9914
Epoch 48/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0219 - acc: 0.9916
Epoch 49/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0244 - acc: 0.9932
Epoch 50/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0311 - acc: 0.9899
Epoch 51/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0200 - acc: 0.9941
Epoch 52/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0269 - acc: 0.9908
Epoch 53/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0204 - acc: 0.9937
Epoch 54/150
8929/8929 [==============================] - 1s 88us/sample - loss: 0.0255 - acc: 0.9909
Epoch 55/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0303 - acc: 0.9910
Epoch 56/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0212 - acc: 0.9927
Epoch 57/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0126 - acc: 0.9959
Epoch 58/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0166 - acc: 0.9940
Epoch 59/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0239 - acc: 0.9918
Epoch 60/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0232 - acc: 0.9916
Epoch 61/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0233 - acc: 0.9925
Epoch 62/150
8929/8929 [==============================] - 1s 99us/sample - loss: 0.0240 - acc: 0.9913
Epoch 63/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0244 - acc: 0.9915
Epoch 64/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0239 - acc: 0.9917
Epoch 65/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0226 - acc: 0.9927
Epoch 66/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0197 - acc: 0.9935
Epoch 67/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0128 - acc: 0.9951
Epoch 68/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0199 - acc: 0.9929
Epoch 69/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0293 - acc: 0.9905
Epoch 70/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0188 - acc: 0.9932
Epoch 71/150
8929/8929 [==============================] - 1s 80us/sample - loss: 0.0166 - acc: 0.9944
Epoch 72/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0199 - acc: 0.9938
Epoch 73/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0200 - acc: 0.9941
Epoch 74/150
8929/8929 [==============================] - 1s 83us/sample - loss: 0.0189 - acc: 0.9937
Epoch 75/150
8929/8929 [==============================] - 1s 81us/sample - loss: 0.0210 - acc: 0.9925
Epoch 76/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0192 - acc: 0.9937
Epoch 77/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0180 - acc: 0.9944
Epoch 78/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0175 - acc: 0.9942
Epoch 79/150
8929/8929 [==============================] - 1s 100us/sample - loss: 0.0155 - acc: 0.9956
Epoch 80/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0433 - acc: 0.9857
Epoch 81/150

8929/8929 [==============================] - 1s 88us/sample - loss: 0.0249 - acc: 0.9922
Epoch 82/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0162 - acc: 0.9946
Epoch 83/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0133 - acc: 0.9953
Epoch 84/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0280 - acc: 0.9907
Epoch 85/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0188 - acc: 0.9927
Epoch 86/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0211 - acc: 0.9932
Epoch 87/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0207 - acc: 0.9933
Epoch 88/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0310 - acc: 0.9904
Epoch 89/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0135 - acc: 0.9959
Epoch 90/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0270 - acc: 0.9897
Epoch 91/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0212 - acc: 0.9931
Epoch 92/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0103 - acc: 0.9966
Epoch 93/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0199 - acc: 0.9942
Epoch 94/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0217 - acc: 0.9920
Epoch 95/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0285 - acc: 0.9913
Epoch 96/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0200 - acc: 0.9937
Epoch 97/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0186 - acc: 0.9934
Epoch 98/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0178 - acc: 0.9937
Epoch 99/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0231 - acc: 0.9929
Epoch 100/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0295 - acc: 0.9908
Epoch 101/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0120 - acc: 0.9964
Epoch 102/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0166 - acc: 0.9956
Epoch 103/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0199 - acc: 0.9929
Epoch 104/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0144 - acc: 0.9955
Epoch 105/150
8929/8929 [==============================] - 1s 92us/sample - loss: 0.0251 - acc: 0.9918
Epoch 106/150
8929/8929 [==============================] - 1s 90us/sample - loss: 0.0223 - acc: 0.9937
Epoch 107/150
8929/8929 [==============================] - 1s 89us/sample - loss: 0.0079 - acc: 0.9980
Epoch 108/150
8929/8929 [==============================] - 1s 87us/sample - loss: 0.0143 - acc: 0.9954
Epoch 109/150
8929/8929 [==============================] - 1s 99us/sample - loss: 0.0209 - acc: 0.9924
Epoch 110/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0257 - acc: 0.9913
Epoch 111/150
8929/8929 [==============================] - 1s 100us/sample - loss: 0.0187 - acc: 0.9945
Epoch 112/150
8929/8929 [==============================] - 1s 116us/sample - loss: 0.0164 - acc: 0.9936
Epoch 113/150
8929/8929 [==============================] - 1s 91us/sample - loss: 0.0165 - acc: 0.9942
Epoch 114/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0276 - acc: 0.9923
Epoch 115/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0159 - acc: 0.9951
Epoch 116/150
8929/8929 [==============================] - 1s 106us/sample - loss: 0.0149 - acc: 0.9948
Epoch 117/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0239 - acc: 0.9927
Epoch 118/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0099 - acc: 0.9961
Epoch 119/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0224 - acc: 0.9932
Epoch 120/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0153 - acc: 0.9955
Epoch 121/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0204 - acc: 0.9927
Epoch 122/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0166 - acc: 0.9946
Epoch 123/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0207 - acc: 0.9918
Epoch 124/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0216 - acc: 0.9924
Epoch 125/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0191 - acc: 0.9929
Epoch 126/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0149 - acc: 0.9951
Epoch 127/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0104 - acc: 0.9969
Epoch 128/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0179 - acc: 0.9943
Epoch 129/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0225 - acc: 0.9925
Epoch 130/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0175 - acc: 0.9938
Epoch 131/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0095 - acc: 0.9960
Epoch 132/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0155 - acc: 0.9952
Epoch 133/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0185 - acc: 0.9951
Epoch 134/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0159 - acc: 0.9945
Epoch 135/150
8929/8929 [==============================] - 1s 98us/sample - loss: 0.0193 - acc: 0.9937
Epoch 136/150
8929/8929 [==============================] - 1s 100us/sample - loss: 0.0179 - acc: 0.9947
Epoch 137/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0135 - acc: 0.9955
Epoch 138/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0085 - acc: 0.9974
Epoch 139/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0216 - acc: 0.9924
Epoch 140/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0167 - acc: 0.9945
Epoch 141/150
8929/8929 [==============================] - 1s 97us/sample - loss: 0.0163 - acc: 0.9944
Epoch 142/150
8929/8929 [==============================] - 1s 96us/sample - loss: 0.0228 - acc: 0.9920
Epoch 143/150
8929/8929 [==============================] - 1s 93us/sample - loss: 0.0178 - acc: 0.9945
Epoch 144/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0145 - acc: 0.9954
Epoch 145/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0118 - acc: 0.9964
Epoch 146/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0224 - acc: 0.9934
Epoch 147/150
8929/8929 [==============================] - 1s 95us/sample - loss: 0.0148 - acc: 0.9959
Epoch 148/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0213 - acc: 0.9941
Epoch 149/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0173 - acc: 0.9946
Epoch 150/150
8929/8929 [==============================] - 1s 94us/sample - loss: 0.0125 - acc: 0.9968

In [33]:

# Testing the model with test set 
ypred = categorical.predict(x_test)

In [34]:
ypred[0]

array([9.9993384e-01, 6.6151610e-05], dtype=float32)

In [35]:
ypred[0]>0.5

array([ True, False])

In [36]:
data.head(100)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
5,42,management,single,tertiary,no,0,yes,yes,unknown,5,may,562,2,-1,0,unknown,yes
6,56,management,married,tertiary,no,830,yes,yes,unknown,6,may,1201,1,-1,0,unknown,yes
7,60,retired,divorced,secondary,no,545,yes,no,unknown,6,may,1030,1,-1,0,unknown,yes
8,37,technician,married,secondary,no,1,yes,no,unknown,6,may,608,1,-1,0,unknown,yes
9,28,services,single,secondary,no,5090,yes,no,unknown,6,may,1297,3,-1,0,unknown,yes
10,38,admin.,single,secondary,no,100,yes,no,unknown,7,may,786,1,-1,0,unknown,yes
11,30,blue-collar,married,secondary,no,309,yes,no,unknown,7,may,1574,2,-1,0,unknown,yes
12,29,management,married,tertiary,no,199,yes,yes,unknown,7,may,1689,4,-1,0,unknown,yes
13,46,blue-collar,single,tertiary,no,460,yes,no,unknown,7,may,1102,2,-1,0,unknown,yes
14,31,technician,single,tertiary,no,703,yes,no,unknown,8,may,943,2,-1,0,unknown,yes
15,35,management,divorced,tertiary,no,3837,yes,no,unknown,8,may,1084,1,-1,0,unknown,yes
16,32,blue-collar,single,primary,no,611,yes,no,unknown,8,may,541,3,-1,0,unknown,yes
17,49,services,married,secondary,no,-8,yes,no,unknown,8,may,1119,1,-1,0,unknown,yes
18,41,admin.,married,secondary,no,55,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
19,49,admin.,divorced,secondary,no,168,yes,yes,unknown,8,may,513,1,-1,0,unknown,yes
20,28,admin.,divorced,secondary,no,785,yes,no,unknown,8,may,442,2,-1,0,unknown,yes
21,43,management,single,tertiary,no,2067,yes,no,unknown,8,may,756,1,-1,0,unknown,yes
22,43,management,divorced,tertiary,no,388,yes,no,unknown,8,may,2087,2,-1,0,unknown,yes
23,43,blue-collar,married,primary,no,-192,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
24,37,unemployed,single,secondary,no,381,yes,no,unknown,8,may,985,2,-1,0,unknown,yes
25,35,blue-collar,single,secondary,no,40,yes,no,unknown,9,may,617,4,-1,0,unknown,yes
26,31,technician,single,tertiary,no,22,yes,no,unknown,9,may,483,3,-1,0,unknown,yes
27,43,blue-collar,single,secondary,no,3,yes,no,unknown,9,may,929,3,-1,0,unknown,yes
28,31,admin.,married,secondary,no,307,yes,no,unknown,9,may,538,1,-1,0,unknown,yes
29,28,blue-collar,single,secondary,no,759,yes,no,unknown,9,may,710,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,60,services,single,primary,no,313,yes,no,unknown,15,may,920,2,-1,0,unknown,yes
71,29,management,married,tertiary,no,10576,no,no,unknown,15,may,1224,2,-1,0,unknown,yes
72,41,retired,divorced,primary,no,-233,yes,no,unknown,15,may,1156,2,-1,0,unknown,yes
73,41,blue-collar,married,primary,no,2453,yes,no,unknown,15,may,1052,1,-1,0,unknown,yes
74,42,technician,single,secondary,no,1364,yes,no,unknown,15,may,1867,6,-1,0,unknown,yes
75,36,services,single,unknown,no,281,yes,no,unknown,16,may,515,1,-1,0,unknown,yes
76,39,technician,married,tertiary,no,94,yes,yes,unknown,16,may,813,1,-1,0,unknown,yes
77,31,self-employed,single,tertiary,no,144,yes,no,unknown,16,may,676,1,-1,0,unknown,yes
78,26,blue-collar,married,secondary,no,246,yes,no,unknown,16,may,1143,3,-1,0,unknown,yes
79,31,blue-collar,married,secondary,no,92,yes,no,unknown,16,may,688,1,-1,0,unknown,yes
80,29,admin.,single,secondary,no,163,yes,yes,unknown,16,may,803,1,-1,0,unknown,yes
81,37,services,divorced,secondary,no,49,yes,no,unknown,16,may,619,2,-1,0,unknown,yes
82,33,blue-collar,single,secondary,no,-416,yes,no,unknown,16,may,767,2,-1,0,unknown,yes
83,24,technician,single,secondary,no,409,yes,no,unknown,16,may,912,1,-1,0,unknown,yes
84,50,admin.,divorced,secondary,no,363,yes,no,unknown,16,may,1340,1,-1,0,unknown,yes
85,27,technician,single,tertiary,no,3706,yes,no,unknown,16,may,897,1,-1,0,unknown,yes
86,54,management,single,tertiary,no,4393,yes,no,unknown,16,may,1297,3,-1,0,unknown,yes
87,30,technician,single,secondary,no,863,yes,no,unknown,16,may,1193,5,-1,0,unknown,yes
88,34,blue-collar,married,primary,no,695,yes,yes,unknown,16,may,1064,4,-1,0,unknown,yes
89,37,management,single,secondary,no,792,yes,no,unknown,16,may,1187,4,-1,0,unknown,yes
90,41,admin.,single,secondary,no,1020,yes,no,unknown,19,may,882,1,-1,0,unknown,yes
91,47,blue-collar,married,secondary,no,863,yes,no,unknown,19,may,943,2,-1,0,unknown,yes
92,31,admin.,married,secondary,no,97,yes,no,unknown,19,may,607,1,-1,0,unknown,yes
93,31,blue-collar,married,secondary,no,754,yes,no,unknown,19,may,1022,4,-1,0,unknown,yes
94,43,services,divorced,secondary,no,1040,yes,no,unknown,19,may,552,3,-1,0,unknown,yes
95,37,management,divorced,tertiary,no,122,yes,no,unknown,19,may,1622,2,-1,0,unknown,yes
96,30,technician,single,tertiary,no,880,yes,yes,unknown,19,may,967,6,-1,0,unknown,yes
97,41,technician,married,secondary,no,501,yes,no,unknown,19,may,579,5,-1,0,unknown,yes
98,36,blue-collar,married,secondary,no,4438,yes,no,unknown,20,may,446,1,-1,0,unknown,yes
99,35,blue-collar,divorced,secondary,no,0,yes,no,unknown,20,may,1205,1,-1,0,unknown,yes

In [37]:

# Testing the model with individual data 
yp = categorical.predict(sc.transform(ct.transform([[40, "management", "married", "secondary", "no", 4025, "yes", "no", "cellular", 15, "jul", 107, 4, -1, 0, "unknown"]])))

In [38]:
yp

array([[1.000000e+00, 6.063072e-13]], dtype=float32)

In [39]:

# Defining a list of categories to present the output in string 
deposits = ['No', 'Yes']
prediction = deposits[np.argmax(yp)]
prediction

'No'

In [40]:

np.argmax(yp)

0